# PostgreSQL - Supabase
spring.datasource.url=${JDBC_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

# Flyway
spring.flyway.enabled=true
spring.flyway.url=${JDBC_URL}
spring.flyway.user=${DB_USER}
spring.flyway.password=${DB_PASSWORD}

# Porta
server.port=${PORT:8080}