# PostgreSQL - Render
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Deixa o Flyway gerenciar o schema, não o Hibernate
spring.jpa.hibernate.ddl-auto=none

# Flyway
spring.flyway.enabled=true
spring.flyway.url=${DATABASE_URL}
spring.flyway.user=${PGUSER}
spring.flyway.password=${PGPASSWORD}

# Porta dinâmica do Render
server.port=${PORT:8080}